TASK_TYPE: train_t2v_entrance
ENABLE: true
use_ema: false
num_workers: 10
frame_lens: [24]
sample_fps: [8]
resolution: [256, 256]
vit_resolution: [224, 224]
lgm_pretrain: './pretrained_models/model.safetensors'

vid_dataset: {
    'type': 'VideoDataset',
    'data_list': ['./data/lvis_thres_28.json', ],
    'data_dir_list': ['/mnt/objaverse/dataset/raw/0', ],
    'caption_dir': './data/text_captions_cap3d.json',
    'vit_resolution': [224, 224],
    'resolution': [256, 256],
    'get_first_frame': True,
    'max_words': 1000,
    'prepare_lgm': True,
}

img_dataset: {
    'type': 'ImageDataset',
    'data_list': ['data/img_list.txt', ],
    'data_dir_list': ['data/images', ],
    'vit_resolution': [224, 224],
    'resolution': [256, 256],
    'max_words': 1000
}
embedder: {
    'type': 'FrozenOpenCLIPTtxtVisualEmbedder',
    'layer': 'penultimate',
    'vit_resolution': [224, 224],
    'pretrained': './pretrained_models/modelscope_t2v/open_clip_pytorch_model.bin'
}

UNet: {
    'type': 'UNetSD_T2VBase',
    'in_dim': 4,
    'y_dim': 1024,
    'upper_len': 128,
    'context_dim': 1024,
    'out_dim': 4,
    'dim_mult': [1, 2, 4, 4],
    'num_heads': 8,
    'default_fps': 8,
    'head_dim': 64,
    'num_res_blocks': 2,
    'dropout': 0.1,
    'misc_dropout': 0.4,
    'temporal_attention': True,
    'temporal_attn_times': 1,
    'use_checkpoint': True,
    'use_fps_condition': False,
    'use_camera_condition': True, # Turn off this if you are trained on multi-view images with fixed poses.
    'use_lgm_refine': False,
    'use_sim_mask': False
}

Diffusion: {
    'type': 'DiffusionDDIM',
    'schedule': 'linear_sd', # cosine
    'schedule_param': {
        'num_timesteps': 1000,
        'init_beta': 0.00085,
        'last_beta': 0.0120,
        'zero_terminal_snr': False,
    },
    'mean_type': 'eps', # eps for baseline with no lgm reg
    'loss_type': 'mse',
    'var_type': 'fixed_small',
    'rescale_timesteps': False,
    'noise_strength': 0.0
}

batch_sizes: {
    "1": 32,
    "24": 8,
}

visual_train: {
    'type': 'VisualTrainTextImageToVideo',
    'partial_keys': [
        ['y', 'fps', 'camera_data', 'gs_data'],
    ],
    'use_offset_noise': False,
    'guide_scale': 9.0, 
}

Pretrain: {
    'type': pretrain_specific_strategies,
    'fix_weight': False,
    'grad_scale': 0.5,
    'resume_checkpoint': './pretrained_models/modelscope_t2v/model_scope_0267000.pth',
    'sd_keys_path': 'data/stable_diffusion_image_key_temporal_attention_x1.json',
}

chunk_size: 4
decoder_bs: 4
lr: 0.00003 # 0.00003

noise_strength: 0.0 # no noise
# classifier-free guidance
p_zero: 0.1
guide_scale: 3.0
num_steps: 1000000

use_zero_infer: True
viz_interval: 50        # 200
save_ckp_interval: 500   # 500

# Log
log_dir: "workspace/experiment_t2v"
log_interval: 1
seed: 0